feat(hr_attenance_missing_contract): init module

diff --git a/task b/task
--- a/task
+++ b/task
@@ -13,22 +13,22 @@ function help() {
     echo
 
     # Define column widths
-    cmd_width=10
-    opt_width=6
-    desc_width=40
+    CMD_WIDTH=10
+    OPT_WIDTH=6
+    DESC_WIDTH=40
+    COLUMN="| %-${CMD_WIDTH}s | %-${OPT_WIDTH}s | %-${DESC_WIDTH}s |\n"
 
     # Print table header
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "Command" "Option" "Description"
-    echo "|$(printf '%*s' $((cmd_width + 2)) '' | tr ' ' '-')|$(printf '%*s' $((opt_width + 2)) '' | tr ' ' '-')|$(printf '%*s' $((desc_width + 2)) '' | tr ' ' '-')|"
+    printf "$COLUMN" "Command" "Option" "Description"
+    echo "|$(printf '%*s' $((CMD_WIDTH + 2)) '' | tr ' ' '-')|$(printf '%*s' $((OPT_WIDTH + 2)) '' | tr ' ' '-')|$(printf '%*s' $((DESC_WIDTH + 2)) '' | tr ' ' '-')|"
 
     # Print table rows
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "all" "" "Run all tasks."
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install" "" "Setup the local environment."
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "lint" "" "Run pre-commit and update index.html."
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "source" "" "Source the Python virtual env."
-    printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "version" "" "Show version of required tools."
-
-    echo
+    printf "$COLUMN" "all" "" "Run all tasks."
+    printf "$COLUMN" "install" "" "Setup the local environment."
+    printf "$COLUMN" "lint" "" "Run pre-commit."
+    printf "$COLUMN" "docs" "" "Update index.html."
+    printf "$COLUMN" "source" "" "Source the Python virtual env."
+    printf "$COLUMN" "version" "" "Show version of required tools."
 }
 
 function version() {
@@ -48,6 +48,11 @@ function lint() {
     echo "Run pre-commit"
     pre-commit run --all-files # --show-diff-on-failure --color=always
 
+}
+
+function docs() {
+    source env/bin/activate
+
     echo "Update index.html for all modules"
     for MODULE in ./*; do
         if [ -f "$MODULE/README.rst" ]; then
@@ -59,27 +64,26 @@ function lint() {
 
 }
 
-case "$1" in
-    help)
-        help
-        ;;
-    all)
-        install
-        lint
-        ;;
-    install)
-        install
-        ;;
-    lint)
-        lint
-        ;;
-    source)
-        source env/bin/activate
-        ;;
-    version)
-        version
-        ;;
-    *)
-        help
-        exit 1;
-esac
+if declare -f "$1" > /dev/null; then
+    "$1" "${@:2}"
+else
+    case "$1" in
+        help)
+            help task
+            exit 1
+            ;;
+        all)
+            install
+            lint
+            docs
+            ;;
+        source)
+            source env/bin/activate
+            ;;
+        *)
+            echo "Unknown command: $1"
+            help task
+            exit 1
+            ;;
+    esac
+fi
